import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    // Individual component entries for granular imports
    "components/alert-dialog": "src/components/alert-dialog.tsx",
    "components/alert": "src/components/alert.tsx",
    "components/avatar": "src/components/avatar.tsx",
    "components/badge": "src/components/badge.tsx",
    "components/breadcrumb": "src/components/breadcrumb.tsx",
    "components/button-group": "src/components/button-group.tsx",
    "components/button": "src/components/button.tsx",
    "components/card-content-with-static-width": "src/components/card-content-with-static-width.tsx",
    "components/card": "src/components/card.tsx",
    "components/checkbox": "src/components/checkbox.tsx",
    "components/collapsible": "src/components/collapsible.tsx",
    "components/combobox": "src/components/combobox.tsx",
    "components/command": "src/components/command.tsx",
    "components/context-menu": "src/components/context-menu.tsx",
    "components/dialog": "src/components/dialog.tsx",
    "components/drawer": "src/components/drawer.tsx",
    "components/dropdown-menu": "src/components/dropdown-menu.tsx",
    "components/empty": "src/components/empty.tsx",
    "components/field": "src/components/field.tsx",
    "components/hover-card": "src/components/hover-card.tsx",
    "components/input-group": "src/components/input-group.tsx",
    "components/input": "src/components/input.tsx",
    "components/item": "src/components/item.tsx",
    "components/label": "src/components/label.tsx",
    "components/menubar": "src/components/menubar.tsx",
    "components/navigation-menu": "src/components/navigation-menu.tsx",
    "components/pagination": "src/components/pagination.tsx",
    "components/popover": "src/components/popover.tsx",
    "components/resizable": "src/components/resizable.tsx",
    "components/scroll-area": "src/components/scroll-area.tsx",
    "components/select": "src/components/select.tsx",
    "components/separator": "src/components/separator.tsx",
    "components/sheet": "src/components/sheet.tsx",
    "components/sidebar": "src/components/sidebar.tsx",
    "components/skeleton": "src/components/skeleton.tsx",
    "components/sonner": "src/components/sonner.tsx",
    "components/spinner": "src/components/spinner.tsx",
    "components/switch": "src/components/switch.tsx",
    "components/table": "src/components/table.tsx",
    "components/tabs": "src/components/tabs.tsx",
    "components/textarea": "src/components/textarea.tsx",
    "components/toggle-group": "src/components/toggle-group.tsx",
    "components/toggle": "src/components/toggle.tsx",
    "components/tooltip": "src/components/tooltip.tsx",
    "components/typography": "src/components/typography.tsx",
    "hooks/use-mobile": "src/hooks/use-mobile.ts",
    "hooks/use-static-width": "src/hooks/use-static-width.ts",
    "lib/utils": "src/lib/utils.ts",
    "lib/with-static-width": "src/lib/with-static-width.tsx",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
  treeshake: true,
  splitting: false,
});
